SET search_path TO inventory;

CREATE TABLE authors (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1001),
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  biography TEXT STORAGE EXTERNAL,
  dob TIMESTAMP
);

-- Taken from https://en.wikipedia.org/wiki/Tom_Wolfe
-- Text is available under the Creative Commons Attribution-ShareAlike 4.0 License (https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License);
INSERT INTO authors (first_name, last_name, biography, dob) VALUES (
    'Tom',
    'Wolfe',
    'Thomas Kennerly Wolfe Jr. (March 2, 1930 – May 14, 2018)[a] was an American author and journalist widely known for his association with New Journalism, a style of news writing and journalism developed in the 1960s and 1970s that incorporated literary techniques. Much of Wolfe''s work is satirical and centers on the counterculture of the 1960s and issues related to class, social status, and the lifestyles of the economic and intellectual elites of New York City.

Wolfe began his career as a regional newspaper reporter in the 1950s, achieving national prominence in the 1960s following the publication of such best-selling books as The Electric Kool-Aid Acid Test (an account of Ken Kesey and the Merry Pranksters) and two collections of articles and essays, The Kandy-Kolored Tangerine-Flake Streamline Baby and Radical Chic & Mau-Mauing the Flak Catchers. In 1979, he published the influential book The Right Stuff about the Mercury Seven astronauts, which was made into a 1983 film of the same name directed by Philip Kaufman.

His first novel, The Bonfire of the Vanities, published in 1987, was met with critical acclaim and also became a commercial success. Its adaptation as a motion picture of the same name, directed by Brian De Palma, was a critical and commercial failure.
Early life and education

Wolfe was born on March 2, 1930, in Richmond, Virginia, the son of Helen Perkins Hughes Wolfe, a garden designer, and Thomas Kennerly Wolfe Sr. (1893–1972), an agronomist and editor of The Southern Planter.[2][3]

He grew up on Gloucester Road in the Richmond North Side neighborhood of Sherwood Park. He recounted childhood memories in a foreword to a book[which?] about the nearby historic Ginter Park neighborhood. He was student council president, editor of the school newspaper, and a star baseball player at St. Christopher''s School, an Episcopal all-boys school in Richmond.[4] In 1991, he wrote another touching remembrance of his childhood in Sherwood Park in a letter to a man who purchased the Wolfe home place.[5]

Upon graduating in 1947, he turned down an offer to enroll at Princeton University to attend Washington and Lee University.[6] At Washington and Lee, Wolfe was a member of the Phi Kappa Sigma fraternity. He majored in English, was sports editor of the college newspaper, and helped found a literary magazine, Shenandoah, giving him opportunities to practice his writing both inside and outside the classroom. Of particular influence was his professor Marshall Fishwick, a teacher of American studies educated at UVA and Yale. More in the tradition of anthropology than literary scholarship, Fishwick taught his students to look at the whole of a culture, including those elements considered profane. Wolfe''s undergraduate thesis, entitled "A Zoo Full of Zebras: Anti-Intellectualism in America," evinced his fondness for words and aspirations toward cultural criticism. Wolfe graduated cum laude in 1951.

While still in college, Wolfe continued playing baseball as a pitcher and began to play semi-professionally. In 1952, he earned a tryout with the New York Giants, but was cut after three days,[2] which he blamed on his inability to throw good fastballs. Wolfe abandoned baseball and instead followed his professor Fishwick''s example, enrolling in Yale University''s American studies doctoral program. His Ph.D. thesis was titled The League of American Writers: Communist Organizational Activity Among American Writers, 1929–1942.[7] In the course of his research, Wolfe interviewed Malcolm Cowley, Archibald MacLeish, and James T. Farrell.[8] A biographer remarked on the thesis: "Reading it, one sees what has been the most baleful influence of graduate education on many who have suffered through it: It deadens all sense of style."[9] Originally rejected, his thesis was finally accepted after he rewrote it in an objective rather than a subjective style. Upon leaving Yale, he wrote a friend, explaining through expletives his personal opinions about his thesis.[10]
Journalism and New Journalism

Though Wolfe was offered teaching jobs in academia, he opted to work as a reporter. In 1956, while still preparing his thesis, Wolfe became a reporter for the Springfield Union in Springfield, Massachusetts. Wolfe finished his thesis in 1957.

In 1959, he was hired by The Washington Post. Wolfe has said that part of the reason he was hired by the Post was his lack of interest in politics. The Post''s city editor was "amazed that Wolfe preferred cityside to Capitol Hill, the beat every reporter wanted." He won an award from The Newspaper Guild for foreign reporting in Cuba in 1961 and also won the Guild''s award for humor. While there, Wolfe experimented with fiction-writing techniques in feature stories.[11]

In 1962, Wolfe left Washington D.C. for New York City, taking a position with the New York Herald Tribune as a general assignment reporter and feature writer. The editors of the Herald Tribune, including Clay Felker of the Sunday section supplement New York magazine, encouraged their writers to break the conventions of newspaper writing.[12] Wolfe attracted attention in 1963 when, three months before the JFK assassination, he published an article on George Ohsawa and the sanpaku condition foretelling death.[13]

During the 1962–63 New York City newspaper strike, Wolfe approached Esquire magazine about an article on the hot rod and custom car culture of southern California. He struggled with the article until his editor, Byron Dobell, suggested that Wolfe send him his notes so they could piece the story together. Wolfe procrastinated. The evening before the deadline, he typed a letter to Dobell explaining what he wanted to say on the subject, ignoring all journalistic conventions. Dobell''s response was to remove the salutation "Dear Byron" from the top of the letter and publish it intact as reportage. The result, published in 1963, was "There Goes (Varoom! Varoom!) That Kandy-Kolored Tangerine-Flake Streamline Baby." The article was widely discussed—loved by some, hated by others. Its notoriety helped Wolfe gain publication of his first book, The Kandy-Kolored Tangerine-Flake Streamline Baby, a collection of his writings from the Herald-Tribune, Esquire, and other publications.[14]

This was what Wolfe called New Journalism, in which some journalists and essayists experimented with a variety of literary techniques, mixing them with the traditional ideal of dispassionate, even-handed reporting. Wolfe experimented with four literary devices not normally associated with feature writing: scene-by-scene construction, extensive dialogue, multiple points of view, and detailed description of individuals'' status-life symbols (the material choices people make) in writing this stylized form of journalism. He later referred to this style as literary journalism.[15] Of the use of status symbols, Wolfe has said, "I think every living moment of a human being''s life, unless the person is starving or in immediate danger of death in some other way, is controlled by a concern for status."[16]

Wolfe also championed what he called "saturation reporting," a reportorial approach in which the journalist "shadows" and observes the subject over an extended period of time. "To pull it off," says Wolfe, "you casually have to stay with the people you are writing about for long stretches ... long enough so that you are actually there when revealing scenes take place in their lives."[17] Saturation reporting differs from "in-depth" and "investigative" reporting, which involve the direct interviewing of numerous sources and/or the extensive analyzing of external documents relating to the story. Saturation reporting, according to communication professor Richard Kallan, "entails a more complex set of relationships wherein the journalist becomes an involved, more fully reactive witness, no longer distanced and detached from the people and events reported."[18]

Wolfe''s The Electric Kool-Aid Acid Test is considered a striking example of New Journalism. This account of the Merry Pranksters, a famous sixties counter-culture group, was highly experimental in Wolfe''s use of onomatopoeia, free association, and eccentric punctuation—such as multiple exclamation marks and italics—to convey the manic ideas and personalities of Ken Kesey and his followers.

In addition to his own work, Wolfe edited a collection of New Journalism with E. W. Johnson, published in 1973 and titled The New Journalism. This book published pieces by Truman Capote, Hunter S. Thompson, Norman Mailer, Gay Talese, Joan Didion, and several other well-known writers, with the common theme of journalism that incorporated literary techniques and which could be considered literature.[19] ',
    '1930-03-01 00:00:00'),

  -- Taken from https://en.wikipedia.org/wiki/Agatha_Christie
  -- Text is available under the Creative Commons Attribution-ShareAlike 4.0 License (https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License);
  (
    'Agatha',
    'Christie',
    '1890–1907: childhood and adolescence

Agatha Mary Clarissa Miller was born on 15 September 1890, into a wealthy upper middle class family in Torquay, Devon. She was the youngest of three children born to Frederick Alvah Miller, "a gentleman of substance",[5] and his wife Clarissa "Clara" Margaret (née Boehmer).[6]: 1–4 [7][8][9]

Christie''s mother Clara was born in Dublin in 1854[a] to British Army officer Frederick Boehmer[12] and his wife Mary Ann (née West). Boehmer died in Jersey in 1863,[b] leaving his widow to raise Clara and her brothers on a meagre income.[13][16]: 10  Two weeks after Boehmer''s death, Mary''s sister, Margaret West, married widowed dry-goods merchant Nathaniel Frary Miller, a US citizen.[17] To assist Mary financially, Margaret and Nathaniel agreed to foster nine-year-old Clara; the family settled in Timperley, Cheshire.[18] The couple had no children together, but Nathaniel had a 17-year-old son, Frederick "Fred", from his previous marriage. Fred was born in New York City and travelled extensively after leaving his Swiss boarding school.[16]: 12  He and Clara were married in London in 1878.[6]: 2–5 [7] Their first child, Margaret "Madge" Frary, was born in Torquay in 1879.[6]: 6 [19] The second, Louis Montant "Monty", was born in Morristown, New Jersey, in 1880,[20] while the family was on an extended visit to the United States.[14]: 7  

When Fred''s father died in 1869,[21] he left Clara £2,000 (approximately equivalent to £230,000 in 2023); in 1881 they used this to buy the leasehold of a villa in Torquay named Ashfield.[22][23] It was here that their third and last child, Agatha, was born in 1890.[6]: 6–7 [9] She described her childhood as "very happy".[14]: 3  The Millers lived mainly in Devon but often visited her step-grandmother/great-aunt Margaret Miller in Ealing and maternal grandmother Mary Boehmer in Bayswater.[14]: 26–31  A year was spent abroad with her family, in the French Pyrenees, Paris, Dinard, and Guernsey.[6]: 15, 24–25  Because her siblings were so much older, and there were few children in their neighbourhood, Christie spent much of her time playing alone with her pets and imaginary companions.[14]: 9–10, 86–88  She eventually made friends with other girls in Torquay, noting that "one of the highlights of my existence" was her appearance with them in a youth production of Gilbert and Sullivan''s The Yeomen of the Guard, in which she played the hero, Colonel Fairfax.[6]: 23–27 

According to Christie, Clara believed she should not learn to read until she was eight; thanks to her curiosity, she was reading by the age of four.[14]: 13  Her sister had been sent to a boarding school, but their mother insisted that Christie receive her education at home. As a result, her parents and sister supervised her studies in reading, writing and basic arithmetic, a subject she particularly enjoyed. They also taught her music, and she learned to play the piano and the mandolin.[6]: 8, 20–21 

Christie was a voracious reader from an early age. Some of her earliest memories were of reading children''s books by Mrs Molesworth and Edith Nesbit. When a little older, she moved on to the surreal verse of Edward Lear and Lewis Carroll.[6]: 18–19  As an adolescent, she enjoyed works by Anthony Hope, Walter Scott, Charles Dickens, and Alexandre Dumas.[14]: 111, 136–37  In April 1901, aged 10, she wrote her first poem, "The Cow Slip".[24]

By 1901, her father''s health had deteriorated, because of what he believed were heart problems.[16]: 33  Fred died in November 1901 from pneumonia and chronic kidney disease.[25] Christie later said that her father''s death when she was 11 marked the end of her childhood.[6]: 32–33 

The family''s financial situation had, by this time, worsened. Madge married the year after their father''s death and moved to Cheadle, Cheshire; Monty was overseas, serving in a British regiment.[16]: 43, 49  Christie now lived alone at Ashfield with her mother. In 1902, she began attending Miss Guyer''s Girls'' School in Torquay but found it difficult to adjust to the disciplined atmosphere.[14]: 139  In 1905, her mother sent her to Paris, where she was educated in a series of pensionnats (boarding schools), focusing on voice training and piano playing. Deciding she lacked the temperament and talent, she gave up her goal of performing professionally as a concert pianist or an opera singer.[16]: 59–61  ',
    '1890-09-15 00:00:00'
  );
